apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: amqp
    name: amqp
  - port: 15672
    targetPort: management
    name: management
  selector:
    app: rabbitmq-server
